version: 0.2

phases:
  pre_build:
    commands:
      - yum update -y
      - yum install -y amazon-linux-extras
      - amazon-linux-extras enable python3.8
      - yum install -y python3.8
      - python3.8 -m pip install --upgrade pip
  build:
    commands:
      - sam build
      - sam deploy --template-file template.yaml --stack-name IMPipeStack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - app.py
    - requirements.txt
    - template.yaml


