version: 0.2

phases:
  build:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y python3.8
      - pip install aws-sam-cli
      - sam build
      - sam deploy --template-file template.yaml --stack-name IMPipeStack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - app.py
    - requirements.txt
    - template.yaml


