version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y python3.8
      - python3.8 -m pip install --upgrade pip
  build:
    commands:
      - sam build
      - sam deploy --template-file template.yaml --stack-name IMPipeStack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - app.py
    - requirements.txt
    - template.yaml


