version: 0.2

phases:
  pre_build:
    commands:
      - sudo yum install -y amazon-linux-extras
      - sudo amazon-linux-extras enable python3.8
      - sudo yum install -y python3.8

  build:
    commands:
      - sam build
      - sam deploy --template-file template.yaml --stack-name IMPipeStack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - app.py
    - requirements.txt
    - template.yaml



