version: 0.2

phases:
  pre_build:
    commands:
      - yum update -y
  build:
    commands:
      - sam build
      - sam deploy --template-file template.yaml --stack-name IMPipeStack --capabilities CAPABILITY_IAM --s3-bucket bucketinventorymanagement

artifacts:
  files:
    - app.py
    - requirements.txt
    - template.yaml


