version: 0.2

phases:
  pre_build:
    commands:
      - --set python /usr/bin/python3.10
      - python3.10 -m pip install --upgrade pip
      - pip3.10 install awscli
  build:
    commands:
      - sam build
      - sam deploy --template-file template.yaml --stack-name IMPipeStack --capabilities CAPABILITY_IAM --s3-bucket bucketinventorymanagement

artifacts:
  files:
    - app.py
    - requirements.txt
    - template.yaml
    - IMLambdafuncsDetails.py
    - IMS3Details.py


